version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  aws-cli: circleci/aws-cli@0.1.17

jobs:
  build-and-push-s3-qa:
    working_directory: ~/pillar-signal-backend # directory where steps will run

    docker: # run the steps with Docker
      - image: maven:3.5.4-jdk-8-alpine

    environment:
      SIGNAL_VERSION: 1.66

    steps:
      - checkout # check out source code to working directory

      - run:
          name: Authenticate with FCM
          command: |
            touch config/firebase-auth.json
            echo "$FIREBASE_AUTH_JSON_BASE64_ENCODED" | base64 -d > config/firebase-auth.json
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: signal-backend-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: signal-backend-{{ checksum "pom.xml" }}

      # create package, but skip tests because last auth changes require lots of test fixes and this service might be replaced soon
      - run: mvn package -DskipTests=true

      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
          path: target/surefire-reports

      - store_artifacts: # store the jar as an artifact
          path: target/TextSecureServer-1.66-bin.tar.gz

      - run:
          name: install curl
          command: apk update && apk add bash python python-dev py-pip curl -y sudo
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: STAGING_AWS_ACCESS_KEY_ID
          aws-secret-access-key: STAGING_AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: Publish Artifact and Notification
          command: |
            export publishedArtifact="$SIGNAL_ARTIFACTORY_URL/signal-backend-$CIRCLE_BUILD_NUM.tar.gz"
            curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD -T target/TextSecureServer-1.66-bin.tar.gz  $publishedArtifact
            chmod +x .circleci/announceRelease.sh && .circleci/announceRelease.sh "SIGNAL-BACKEND-QA" "$publishedArtifact"
      - run:
          name: Push txt file to S3 bucket
          command: |
            touch pillar-signal-backend.txt
            echo "$SIGNAL_ARTIFACTORY_URL/signal-backend-$CIRCLE_BUILD_NUM.tar.gz" > pillar-signal-backend.txt
            aws --region $AWS_DEFAULT_REGION s3 cp pillar-signal-backend.txt $QA_RELEASE_BUCKET
      - run:
          name: Announce Deployment
          command: |
            chmod +x .circleci/announceDeployment.sh
            .circleci/announceDeployment.sh "SIGNAL-BACKEND" "QA" "$(cat ./pillar-signal-backend.txt)"
      - slack/status:
          fail_only: false
          failure_message: "Ooops! The *$CIRCLE_JOB* job has failed! :circleci-fail:"
          success_message: "The *$CIRCLE_JOB* job has succeeded! :circleci-pass:"
          only_for_branches: develop,master
          webhook: "${SLACK_WEBHOOK_URL}"

  build-production:
    working_directory: ~/pillar-signal-backend # directory where steps will run

    docker: # run the steps with Docker
      - image: maven:3.5.4-jdk-8-alpine

    environment:
      SIGNAL_VERSION: 1.66

    steps:
      - checkout # check out source code to working directory

      - run:
          name: Authenticate with FCM
          command: |
            touch config/firebase-auth.json
            echo "$FIREBASE_AUTH_JSON_BASE64_ENCODED" | base64 -d > config/firebase-auth.json
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: signal-backend-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: signal-backend-{{ checksum "pom.xml" }}

      # create package, but skip tests because last auth changes require lots of test fixes and this service might be replaced soon
      - run: mvn package -DskipTests=true

      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
          path: target/surefire-reports

      - store_artifacts: # store the jar as an artifact
          path: target/TextSecureServer-1.66-bin.tar.gz

      - run:
          name: install curl
          command: apk update && apk add bash python python-dev py-pip curl -y sudo
      - run:
          name: Publish Artifact and Notification
          command: |
            export publishedArtifact="$SIGNAL_ARTIFACTORY_URL/signal-backend-$CIRCLE_BUILD_NUM.tar.gz"
            curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD -T target/TextSecureServer-1.66-bin.tar.gz  $publishedArtifact
            chmod +x .circleci/announceRelease.sh && .circleci/announceRelease.sh "SIGNAL-BACKEND" "$publishedArtifact"
      - slack/status:
          fail_only: false
          failure_message: "Ooops! The *$CIRCLE_JOB* job has failed! :circleci-fail:"
          success_message: "The *$CIRCLE_JOB* job has succeeded! :circleci-pass:"
          only_for_branches: develop,master
          webhook: "${SLACK_WEBHOOK_URL}"

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build-and-push-s3-qa:
          filters:
            branches:
              only:
                - develop
      - build-production:
          filters:
            branches:
              only:
                - master
