version: 2
jobs:
  whitesource:
    working_directory: ~/pillar-signal-backend
    docker:
      - image: circleci/openjdk:8-node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/pillar-signal-backend/workspace
      - run :
          name: Setup WhiteSource
          command: curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/wss_agent.sh
      - run:
          name: execute whitesource
          command: |
            cd .whitesource/
            chmod +x wss_agent.sh && ./wss_agent.sh -apiKey $WHITESOURCE_API_KEY -c ./whitesource-fs-agent.config  -project pillar-signal-backend -f files.list

  build-and-push-s3-qa:

    working_directory: ~/pillar-signal-backend # directory where steps will run

    docker: # run the steps with Docker
      - image: maven:3.5.4-jdk-8-alpine

    environment:
      SIGNAL_VERSION: 1.66

    steps:

      - checkout # check out source code to working directory

      - run:
          name: Authenticate with FCM
          command: |
            touch config/firebase-auth.json
            echo "$FIREBASE_AUTH_JSON_BASE64_ENCODED" | base64 -d > config/firebase-auth.json
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: signal-backend-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: signal-backend-{{ checksum "pom.xml" }}

      - run: mvn package # run the actual tests

      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
          path: target/surefire-reports

      - store_artifacts: # store the jar as an artifact
          path: target/TextSecureServer-1.66-bin.tar.gz

      - run:
          name: install curl
          command: apk update && apk add bash python python-dev py-pip -y sudo
      - run:
          name: Install AWS CLI
          command: |
            pip install awscli --upgrade --user
      - run:
          name: Publish Artifact and Notification
          command: |
            export publishedArtifact="$SIGNAL_ARTIFACTORY_URL/signal-backend-$CIRCLE_BUILD_NUM.tar.gz"
            curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD -T target/TextSecureServer-1.66-bin.tar.gz  $publishedArtifact
            chmod +x .circleci/announceRelease.sh && .circleci/announceRelease.sh "SIGNAL-BACKEND-QA" "$publishedArtifact"
      - run:
          name: Push txt file to S3 bucket
          command: |
            touch pillar-signal-backend.txt
            echo "$SIGNAL_ARTIFACTORY_URL/signal-backend-$CIRCLE_BUILD_NUM.tar.gz" > pillar-signal-backend.txt
            export AWS_ACCESS_KEY_ID=$STAGING_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$STAGING_AWS_SECRET_ACCESS_KEY
            /root/.local/bin/aws s3 cp pillar-signal-backend.txt $STAGING_RELEASE_BUCKET
            /root/.local/bin/aws s3 cp pillar-signal-backend.txt $QA_RELEASE_BUCKET
      - run:
          name: Announce Deployment
          command: |
            chmod +x .circleci/announceDeployment.sh
            .circleci/announceDeployment.sh "SIGNAL-BACKEND" "QA" "$(cat ./pillar-signal-backend.txt)"
  build-production:

    working_directory: ~/pillar-signal-backend # directory where steps will run

    docker: # run the steps with Docker
      - image: maven:3.5.4-jdk-8-alpine

    environment:
      SIGNAL_VERSION: 1.66

    steps:

      - checkout # check out source code to working directory

      - run:
          name: Authenticate with FCM
          command: |
            touch config/firebase-auth.json
            echo "$FIREBASE_AUTH_JSON_BASE64_ENCODED" | base64 -d > config/firebase-auth.json
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: signal-backend-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: signal-backend-{{ checksum "pom.xml" }}

      - run: mvn package # run the actual tests

      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
          path: target/surefire-reports

      - store_artifacts: # store the jar as an artifact
          path: target/TextSecureServer-1.66-bin.tar.gz


      - run:
          name: Publish Artifact and Notification
          command: |
            export publishedArtifact="$SIGNAL_ARTIFACTORY_URL/signal-backend-$CIRCLE_BUILD_NUM.tar.gz"
            curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD -T target/TextSecureServer-1.66-bin.tar.gz  $publishedArtifact
            chmod +x .circleci/announceRelease.sh && .circleci/announceRelease.sh "SIGNAL-BACKEND" "$publishedArtifact"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - whitesource
      - build-and-push-s3-qa:
          filters:
            branches:
              only:
                - fix/circleci-deploy-job
      - build-production:
          filters:
            branches:
              only:
                - master
